project:
  type: website
  output-dir: docs


website:
  favicon: assets/favicon.ico
  title: "GTPN Website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - pages/events.qmd

  page-footer: 
    center:
      - text: "Contact Us"
        href: pages/contactus.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



