---
title: "GTPN Website"
---

Global Tibetan Professionals Network (GTPN) is a platform where Tibetan professionals from diverse backgrounds can network with each other and find creative ways of contributing to the community.  Through this network, Tibetan professionals around the world can share ideas, information and resources among themselves and with those aspiring to become like them through mentorship.

Launched on Nov 1, 2008 with support from Bureau of His Holiness the Dalai Lama, New Delhi, today GTPN has five active chapters: GTPN Delhi, Bangalore, Toronto, New York and London. There are currently 411 registered GTPN members.

## VISION
To promote specialisation and professionalism among Tibetans to strengthen the Community

## MISSION
To create a global network of Tibetan professionals and connect them with the community

## OBJECTIVES 
ENVISION’s main objectives for establishing the GTPN are as follows:

To create a global network of Tibetan professionals and connect them with the community
To identify and promote Tibetans who have achieved success in different professions as role models
To promote the involvement of Tibetan professionals in sustaining Tibetan identify and strengthening the Tibetan voice

## WHY JOIN GTPN?
Networking opportunities
GTPN membership will provide a platform for Tibetan professionals to network with others sharing similar career interests and challenges as well as those in different fields. Tibetan professionals can benefit from each other by exchange of ideas, information and resources. The skills, knowledge and experiences of the successful Tibetan professionals will be a resource to the younger professionals.

## Connect and contribute to the community
Due to lack of a proper channel of communication, many Tibetan professionals wishing to contribute to the community do not know where to begin. GTPN can connect them to the community as well as support their involvement in community development.

One of the specific ways in which the professionals can help the community is by mentoring younger Tibetans interested in similar career lines.  Mentoring can happen one on one and also through meetings and workshops.

GTPN can also establish links with the Central Tibetan Administration in Dharamshala as well as other Tibetan institutes and schools to explore other ways of contributing to the community

## Conferences and Event
Chapters organise networking events where members meet to exchange ideas, resources and have discussions on relevant topics.

ENVISION which serves as the umbrella body for GTPN will facilitate conferences and events from time to time where GTPN members will be invited.  These events will serve as a great opportunity for networking and sharing resources with other professionals.

Check our [Events Page](pages/events.qmd) for upcoming events and more information.

## Who is eligible for GTPN membership?
Any Tibetan professional willing to share ideas, information and resources with other Tibetan professionals
Any Tibetan professional with a deep sense of commitment to contribute to the community
WHO IS A PROFESSIONAL?
- A person who is into a body of knowledge which requires a certain skill-set and which has been acquired through, either academic qualification or experience over a period of time.

## FUTURE GOALS
Create various professional forums to draw upon the skills and experiences of Tibetan professionals
Provide platforms for Tibetan professionals to come together to exchange ideas and resources as well as to contribute to the community.